w:int = 1
x:int = 1
y:int = 2
printf("%d", w == x)
printf("%d", y != x)
printf("%d", y > x)
printf("%d", y >= x)
printf("%d", w >= x)
printf("%d", x < y)
printf("%d", x <= y)
printf("%d", w <= x)
printf("%d", w + x == y)
printf("%d", y - x == w)
printf("%d", w * x == x)
printf("%d", 5 % 2 == x)
printf("%d", not False)
printf("%d", not (w != x))
printf("%d", -x == -1)
printf("%d", True and True)
printf("%d", True or False)
printf("%d", False or True)
printf("%d", (False or True) and True)
printf("%d", True if x != y else False)
printf("%d\n", False if x == y else True)
